// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNhBOZ-wiSWXtIamASbFFapX36XmB5QLk',
    appId: '1:121245951217:web:f04afc576604a119c93550',
    messagingSenderId: '121245951217',
    projectId: 'modul4-232ae',
    authDomain: 'modul4-232ae.firebaseapp.com',
    storageBucket: 'modul4-232ae.appspot.com',
    measurementId: 'G-HHGRVJXQDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlE7JLKL_XMS9xRhgfwe41jfzOY7GVECs',
    appId: '1:121245951217:android:405a0fa0904422bdc93550',
    messagingSenderId: '121245951217',
    projectId: 'modul4-232ae',
    storageBucket: 'modul4-232ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDuBrZ4sGzyU2dm50I9A097Ie8z91S52o',
    appId: '1:121245951217:ios:8248769fc1eeba73c93550',
    messagingSenderId: '121245951217',
    projectId: 'modul4-232ae',
    storageBucket: 'modul4-232ae.appspot.com',
    iosBundleId: 'DemoModul2.demoModul2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDuBrZ4sGzyU2dm50I9A097Ie8z91S52o',
    appId: '1:121245951217:ios:03f9f19336662dcfc93550',
    messagingSenderId: '121245951217',
    projectId: 'modul4-232ae',
    storageBucket: 'modul4-232ae.appspot.com',
    iosBundleId: 'DemoModul2.demoModul2.RunnerTests',
  );
}
